export const abgCases = [
  {
    name: "A falling bicarbonate",
    ph: "7.29",
    co2: 26,
    bicarbonate: 12,
    sodium: 140,
    chloride: 104,
    direction: "Acidemia",
    process: "Metabolic acidosis with expected respiratory compensation",
    reasoning:
      "Low bicarbonate explains the acidemia. Winter’s range is 24–28 mmHg; measured PaCO₂ is 26. The anion gap is 24 mmol/L. This is elevated against our teaching reference of 8–12 (normal albumin assumed), but does not identify the cause.",
    winter: true,
  },
  {
    name: "CO₂ that looks normal",
    ph: "7.10",
    co2: 40,
    bicarbonate: 12,
    sodium: 140,
    chloride: 104,
    direction: "Acidemia",
    process: "Metabolic acidosis plus respiratory acidosis",
    reasoning:
      "A PaCO₂ of 40 is near the usual baseline but is too high for bicarbonate 12. Winter’s range is 24–28. The CO₂ therefore suggests an additional respiratory acidosis, rather than adequate compensation.",
    winter: true,
  },
  {
    name: "A near-normal pH",
    ph: "7.45",
    co2: 18,
    bicarbonate: 12,
    sodium: 140,
    chloride: 104,
    direction: "Within the reference interval",
    process: "Metabolic acidosis plus respiratory alkalosis",
    reasoning:
      "The pH is at the upper boundary of our reference interval. Bicarbonate is low, and PaCO₂ is below Winter’s 24–28 range. Opposing metabolic acidosis and respiratory alkalosis can hide behind a near-normal pH.",
    winter: true,
  },
  {
    name: "A recent rise in CO₂",
    ph: "7.26",
    co2: 60,
    bicarbonate: 26,
    sodium: 140,
    chloride: 104,
    direction: "Acidemia",
    process: "Acute respiratory acidosis",
    reasoning:
      "High CO₂ explains the acidemia. In an acute respiratory acidosis, bicarbonate often rises about 1–2 mmol/L per 10 mmHg CO₂ increase. A rise from 24 to 26 is compatible with an acute response to CO₂ increasing from 40 to 60. Duration and clinical context matter.",
    winter: false,
  },
  {
    name: "A recent fall in CO₂",
    ph: "7.49",
    co2: 30,
    bicarbonate: 22,
    sodium: 140,
    chloride: 108,
    direction: "Alkalemia",
    process: "Acute respiratory alkalosis",
    reasoning:
      "Low CO₂ explains alkalemia. A fall in bicarbonate of about 1–2 mmol/L per 10 mmHg acute CO₂ decrease is expected. Here, CO₂ falls from 40 to 30 and bicarbonate from 24 to 22. Winter’s formula is for metabolic acidosis, so it is not used here.",
    winter: false,
  },
  {
    name: "A rising bicarbonate",
    ph: "7.50",
    co2: 48,
    bicarbonate: 36,
    sodium: 140,
    chloride: 94,
    direction: "Alkalemia",
    process: "Metabolic alkalosis with expected respiratory compensation",
    reasoning:
      "Raised bicarbonate explains alkalemia. PaCO₂ commonly rises about 0.6–0.75 mmHg per 1 mmol/L bicarbonate rise. A 12 mmol/L rise predicts a CO₂ increase of about 7–9 mmHg. PaCO₂ 48 is compatible with that response.",
    winter: false,
  },
];
