// Curriculum navigation only: planned coverage is not a published lesson or review approval.
export type CurriculumLink = { title: string; href: string };
export type CurriculumStage = { id: string; title: string; description: string; links: CurriculumLink[]; planned?: string[] };
export type CurriculumOrder = { reason: string; sampleLesson: string; stages: CurriculumStage[]; orientation?: CurriculumLink[]; orientationPreparation?: string };

export const curriculumOrders: Record<string, CurriculumOrder> = {
  "histology": {
    reason: "Learn a systematic identification method before applying it to individual organs and microscope sections.",
    sampleLesson: "histology-foundations-tissues",
    stages: [
      { id: "stage-1", title: "Tissue families",
        description: "Compare epithelial, connective, muscle and nervous tissue using independent structural clues.",
        links: [{"title":"Tissue families","href":"/library/histology-foundations-tissues"}],
      },
      { id: "stage-2", title: "Reading sections",
        description: "Establish preparation, scale and orientation before interpreting a profile.",
        links: [{"title":"Reading sections","href":"/library/microscopy"}],
      },
      { id: "stage-3", title: "Linings and support",
        description: "Connect epithelial layers and cell shape with connective-tissue support.",
        links: [{"title":"Linings and support","href":"/library/epithelia"}],
      },
      { id: "stage-4", title: "Muscle and nervous tissue",
        description: "Distinguish contractile tissues, then study neurons, glia and myelin.",
        links: [{"title":"Muscle and nervous tissue","href":"/library/muscle-histology"}],
      },
      { id: "stage-5", title: "Organ identification",
        description: "Use tissue architecture to reason from a section to an organ and its function.",
        links: [{"title":"Organ identification","href":"/library/renal-histology"}],
      },
    ],
    orientation: [{"title":"Recognise the four basic tissues","href":"/library/histology-foundations-tissues"},{"title":"Read a histology section","href":"/library/microscopy"},{"title":"Classify epithelia","href":"/library/epithelia"}],
    orientationPreparation: "Begin with the four basic tissues, then practise reading sections with microscopy, epithelia and connective tissue before moving to organs.",
  },
  "anatomy": {
    reason: "Establish position, directions, planes and compartments before starting the regional course below.",
    sampleLesson: "anatomy-foundations",
    stages: [
      { id: "anatomy-foundations", title: "Foundations",
        description: "Position, directions, planes, cavities and tissue-to-organ organisation. Begin here; no previous Anatomy lesson is required.",
        links: [{"title":"Foundations","href":"/library/anatomy-foundations"}],
      },
      { id: "thoracic-cage-landmarks", title: "Thorax",
        description: "Use landmarks to orient the chest, then connect its wall, lungs, heart and major pathways.",
        links: [{"title":"Thorax","href":"/library/thoracic-cage-landmarks"}],
      },
      { id: "abdominal-surface-map", title: "Abdomen",
        description: "Move from surface regions to organ relations, peritoneal organisation and vessels.",
        links: [{"title":"Abdomen","href":"/library/abdominal-surface-map"}],
      },
      { id: "pelvic-boundaries", title: "Pelvis and urogenital anatomy",
        description: "Establish boundaries before studying support, urinary pathways and reproductive structures.",
        links: [{"title":"Pelvis and urogenital anatomy","href":"/library/pelvic-boundaries"}],
      },
      { id: "neck-triangles", title: "Head, neck and neuroanatomy",
        description: "Organise complex relationships by regions, fascial spaces and nerve pathways.",
        links: [{"title":"Head, neck and neuroanatomy","href":"/library/neck-triangles"}],
      },
      { id: "bones-and-connections", title: "Musculoskeletal anatomy",
        description: "Connect bones and joints to muscle actions, limb compartments and neurovascular routes.",
        links: [{"title":"Musculoskeletal anatomy","href":"/library/bones-and-connections"}],
      },
    ],
    orientation: [{"title":"Anatomy foundations: position, planes and organisation","href":"/library/anatomy-foundations"},{"title":"Identify thoracic cage landmarks","href":"/library/thoracic-cage-landmarks"},{"title":"Choose a volume in the 120-lesson course","href":"/study/anatomy/guide"}],
    orientationPreparation: "Begin with anatomical position, directions, planes, body cavities and tissue-to-organ organisation. Then apply this framework to the five regional volumes.",
  },
  "physiology": {
    reason: "Start with the regulated internal environment and body-fluid compartments. Then use membrane mechanisms and excitable cells to explain organ systems; study blood and haemostasis after that shared framework.",
    sampleLesson: "physiology-membrane-foundations",
    stages: [
      { id: "homeostasis-fluids", title: "Homeostasis and body fluids",
        description: "Start here: distinguish amount, concentration and compartment before reasoning about regulation. The short orientation and measurement lesson cover part of this foundation.",
        links: [{"title":"Compartment, gradient and control: short orientation","href":"/learn/foundations/physiology"},{"title":"Measure body-fluid compartments","href":"/library/indicator-dilution"}],
        planned: ["Full homeostasis and body-fluid foundation"],
      },
      { id: "membranes", title: "Membrane structure, transport and resting potential",
        description: "Connect permeability and energy with movement across a membrane, then explain resting voltage.",
        links: [{"title":"Membrane transport and resting potential","href":"/library/physiology-membrane-foundations"},{"title":"Transport mechanisms and permeability","href":"/library/fluid-and-membrane-transport"},{"title":"Resting potential and passive spread","href":"/library/membrane-potentials"}],
      },
      { id: "excitable-cells", title: "Action potentials, synapses, muscle and autonomic control",
        description: "Follow a signal from membrane excitation through communication and contraction to autonomic regulation.",
        links: [{"title":"Action potentials in excitable cells","href":"/library/biophysics-action-potentials"},{"title":"Synaptic transmission and integration","href":"/library/synaptic-integration"},{"title":"Muscle excitation and contraction","href":"/library/muscle-contraction"},{"title":"Autonomic signalling","href":"/library/autonomic-signalling"}],
      },
      { id: "cardiovascular", title: "Cardiovascular",
        description: "Use pressure, flow and feedback to connect the cardiac cycle with tissue perfusion.",
        links: [{"title":"The cardiac cycle","href":"/library/cardiac-cycle"},{"title":"Cardiac output","href":"/library/cardiac-output"},{"title":"Arterial baroreflex","href":"/library/baroreflex"},{"title":"Microcirculation and fluid exchange","href":"/library/lymph-and-fluid-exchange"},{"title":"ECG time and vectors","href":"/library/ecg-time-and-vectors"}],
      },
      { id: "respiratory", title: "Respiratory",
        description: "Connect ventilation mechanics with alveolar ventilation and gas exchange.",
        links: [{"title":"Respiratory mechanics","href":"/library/respiratory-mechanics"},{"title":"Alveolar ventilation calculations","href":"/library/alveolar-ventilation-calculations"},{"title":"Ventilation and perfusion","href":"/library/ventilation-perfusion"}],
      },
      { id: "renal", title: "Renal and acid-base",
        description: "Apply transport and circulation to filtration, water balance and acid-base regulation.",
        links: [{"title":"Eight-lesson renal and acid-base course","href":"/learn/renal"},{"title":"Renal water balance","href":"/library/renal-water-balance"}],
      },
      { id: "digestion-energy", title: "Gastrointestinal and energy balance",
        description: "Connect digestive movement and secretion with nutrient handling and energy balance.",
        links: [{"title":"Digestive control","href":"/library/digestive-control"},{"title":"Energy balance","href":"/library/energy-balance"}],
      },
      { id: "endocrine-reproduction", title: "Endocrine and reproduction",
        description: "Apply feedback reasoning to hormonal axes and reproductive cycles.",
        links: [{"title":"Endocrine feedback","href":"/library/endocrine-feedback"},{"title":"Reproductive cycles","href":"/library/reproductive-cycles"}],
      },
      { id: "nervous-senses", title: "Nervous system and special senses",
        description: "Build on earlier signalling mechanisms to trace sensory pathways and stimulus coding.",
        links: [{"title":"Somatosensory pathways","href":"/library/somatosensory-pathways"},{"title":"Special senses","href":"/library/special-senses"}],
      },
      { id: "blood", title: "Blood and haemostasis",
        description: "Finish by connecting endothelial restraint, platelet responses and clot stabilisation with the wider circulation.",
        links: [{"title":"Blood and haemostasis","href":"/library/blood-and-haemostasis"}],
      },
    ],
  },
  "biochemistry": {
    reason: "Start with water, acid-base chemistry and thermodynamics, then molecular structure and interactions. These foundations make enzyme kinetics and metabolic pathways easier to interpret without confusing energy with reaction rate.",
    sampleLesson: "biochemistry-enzyme-foundations",
    stages: [
      { id: "chemical-foundations", title: "Water, pH, buffers and thermodynamics",
        description: "Start here: use the existing water and thermodynamics lessons as shared preparation. An integrated pH and buffer foundation is still planned.",
        links: [{"title":"Shared preparation: water and protein interactions","href":"/library/biophysics-water-biopolymers"},{"title":"Thermodynamic systems and the first law","href":"/library/biophysics-energy-first-law"},{"title":"Entropy, free energy and equilibrium","href":"/library/biophysics-entropy-potentials"}],
        planned: ["pH, buffers and integrated chemical foundation"],
      },
      { id: "proteins", title: "Amino acids, proteins and molecular interactions",
        description: "Use existing protein-structure teaching while the broader amino-acid and interaction foundation is planned.",
        links: [{"title":"Protein structure and collagen","href":"/library/protein-structure"},{"title":"Shared preparation: molecular interactions","href":"/library/biophysics-molecular-interactions"}],
        planned: ["Amino-acid chemistry and molecular interactions foundation"],
      },
      { id: "enzymes", title: "Enzymes and kinetics",
        description: "Connect catalysis, saturation and regulation before interpreting pathway flux.",
        links: [{"title":"Enzymes, kinetics and regulation","href":"/library/biochemistry-enzyme-foundations"},{"title":"Enzyme catalysis and inhibition","href":"/library/enzyme-kinetics"}],
      },
      { id: "carbohydrates-lipids", title: "Carbohydrates and lipids",
        description: "Establish molecular building blocks before studying their interconversion and use as fuels.",
        links: [],
        planned: ["Carbohydrate and lipid chemistry foundation"],
      },
      { id: "bioenergetics", title: "Bioenergetics",
        description: "Connect energy coupling, redox carriers and membranes before following central metabolism.",
        links: [],
        planned: ["Bioenergetics and oxidative phosphorylation foundation"],
      },
      { id: "central-metabolism", title: "Central metabolism",
        description: "Reuse the existing carbon and lipid pathways, distinguishing synthesis, oxidation and transport.",
        links: [{"title":"Glycolysis and lactate recycling","href":"/library/glycolysis"},{"title":"Pyruvate dehydrogenase and the TCA cycle","href":"/library/pdh-tca"},{"title":"Lipid metabolism","href":"/library/lipid-metabolism"},{"title":"Ketone production and use","href":"/library/ketone-production-and-use"},{"title":"Lipoprotein routes","href":"/library/lipoprotein-routes"}],
      },
      { id: "nucleotide-nitrogen", title: "Nucleotide and nitrogen metabolism",
        description: "Connect amino-group transfer and nitrogen disposal; nucleotide metabolism remains a coverage gap.",
        links: [{"title":"Nitrogen metabolism","href":"/library/nitrogen-metabolism"}],
        planned: ["Nucleotide synthesis and degradation"],
      },
      { id: "integrated-clinical", title: "Integrated clinical biochemistry",
        description: "Bring tissue metabolism and biochemical measurements together after the underlying mechanisms.",
        links: [],
        planned: ["Integrated clinical biochemistry and laboratory interpretation"],
      },
    ],
  },
  "genetics": {
    reason: "Build a precise vocabulary for DNA, alleles and expression before studying inheritance patterns and immune mechanisms.",
    sampleLesson: "genetics-genome-foundations",
    stages: [
      { id: "stage-1", title: "Genome and expression",
        description: "Distinguish the DNA sequence, its inheritance and its expressed products.",
        links: [{"title":"Genome and expression","href":"/library/genetics-genome-foundations"}],
      },
      { id: "stage-2", title: "Meiosis and inheritance",
        description: "Follow segregation before calculating inheritance probabilities.",
        links: [{"title":"Meiosis and inheritance","href":"/library/meiosis"}],
      },
      { id: "stage-3", title: "Genetic interpretation",
        description: "Connect a testing method with the biological question it can answer.",
        links: [{"title":"Genetic interpretation","href":"/library/genetic-testing"}],
      },
      { id: "stage-4", title: "Innate and adaptive immunity",
        description: "Begin the immunology strand with recognition, activation and memory.",
        links: [{"title":"Innate and adaptive immunity","href":"/library/innate-adaptive"}],
      },
      { id: "stage-5", title: "Antigens and effectors",
        description: "Connect antigen presentation with T cells, then study complement and hypersensitivity.",
        links: [{"title":"Antigens and effectors","href":"/library/antigen-presentation"}],
      },
    ],
    orientation: [{"title":"Genome, inheritance and gene expression","href":"/library/genetics-genome-foundations"},{"title":"Reason through inheritance","href":"/library/inheritance"},{"title":"Compare innate and adaptive responses","href":"/library/innate-adaptive"}],
    orientationPreparation: "For genetics, begin with genome organisation, expression and inheritance, then study meiosis. For immunology, begin with innate and adaptive responses before antigen presentation.",
  },
  "biophysics": {
    reason: "Start with gradients, geometry and permeability, then progress to the existing theory and practical course.",
    sampleLesson: "biophysics-membrane-foundations",
    stages: [
      { id: "stage-1", title: "Diffusion and membranes",
        description: "State the moving substance, permeability and boundary conditions before calculating.",
        links: [{"title":"Diffusion and membranes","href":"/library/biophysics-membrane-foundations"}],
      },
      { id: "stage-2", title: "Light and image formation",
        description: "Establish units and optical principles before using lenses and instruments.",
        links: [{"title":"Light and image formation","href":"/library/biophysics-radiation-optics"}],
      },
      { id: "stage-3", title: "Flow and electrical signals",
        description: "Use pressure, resistance and membrane models to explain transport and signalling.",
        links: [{"title":"Flow and electrical signals","href":"/library/biophysics-fluid-flow"}],
      },
      { id: "stage-4", title: "Medical imaging",
        description: "Connect physical interactions and measured signals with an image.",
        links: [{"title":"Medical imaging","href":"/library/biophysics-ct-imaging"}],
      },
      { id: "stage-5", title: "Practical measurement",
        description: "Test a transport prediction and distinguish the model from the measured quantity.",
        links: [{"title":"Practical measurement","href":"/library/biophysics-practical-diffusion"}],
      },
    ],
    orientation: [{"title":"Diffusion, osmosis and membranes","href":"/library/biophysics-membrane-foundations"},{"title":"Form an image","href":"/library/biophysics-image-formation"},{"title":"Explain wave optics","href":"/library/biophysics-wave-optics"}],
    orientationPreparation: "Begin with diffusion, osmosis and membranes. Review units and rearranging equations, then follow the theory and practical sequences.",
  },
  "cell-biology": {
    reason: "Start with how a cell is organised, then locate membranes, organelles and energy transfer before following DNA, RNA and proteins. Existing molecular lessons remain available while the earlier foundations are planned.",
    sampleLesson: "dna-replication",
    stages: [
      { id: "cell-organisation", title: "Cell organisation",
        description: "Start here: establish cellular compartments and how their functions connect before tracing molecular processes.",
        links: [],
        planned: ["Cell organisation foundation"],
      },
      { id: "membranes", title: "Membranes and transport",
        description: "Reuse the existing membrane foundation as shared preparation; a cell-biology overview remains to be developed.",
        links: [{"title":"Shared foundation: membranes and transport","href":"/library/physiology-membrane-foundations"}],
        planned: ["Cell-biology membrane organisation overview"],
      },
      { id: "organelles-energy", title: "Organelles and energy",
        description: "Locate organelles and their roles before studying energy conversion and intracellular destinations.",
        links: [],
        planned: ["Organelle organisation and cellular energy foundation"],
      },
      { id: "dna-chromatin", title: "DNA and chromatin",
        description: "Connect genetic information with chromosome packaging and access.",
        links: [{"title":"Chromatin access, packaging and topology","href":"/library/chromatin-access-and-topology"}],
      },
      { id: "replication-repair", title: "Replication and repair",
        description: "Follow strand direction and copying before considering DNA damage and repair.",
        links: [{"title":"DNA replication","href":"/library/dna-replication"},{"title":"DNA repair","href":"/library/dna-repair"}],
      },
      { id: "transcription-rna", title: "Transcription and RNA processing",
        description: "Distinguish RNA synthesis from the processing that produces a mature message.",
        links: [{"title":"RNA processing","href":"/library/rna-processing"}],
        planned: ["Transcription and transcriptional control foundation"],
      },
      { id: "translation-targeting", title: "Translation and protein targeting",
        description: "Follow decoding, targeting and trafficking, then examine quality control.",
        links: [{"title":"Translation","href":"/library/translation"},{"title":"Protein targeting and trafficking","href":"/library/protein-trafficking"},{"title":"ER protein quality control","href":"/library/er-protein-quality-control"}],
      },
      { id: "cell-control-methods", title: "Cell cycle, signalling, apoptosis and methods",
        description: "Connect cellular decisions with the methods used to investigate molecular processes.",
        links: [{"title":"Cell signalling","href":"/library/cell-signaling"},{"title":"PCR, qPCR and reverse transcription","href":"/library/pcr"}],
        planned: ["Cell cycle and apoptosis foundation"],
      },
    ],
  },
};
// An existing sampler remains available independently of a planned first foundation.
export function curriculumStartHref(subject: string) {
  const order = curriculumOrders[subject];
  return order.orientation?.[0].href ?? `/study/${subject}#subject-topic-map`;
}

export const beginnerLinks: Record<string, CurriculumLink[]> = Object.fromEntries(
  Object.entries(curriculumOrders).map(([subject, order]) => [subject, order.orientation ??
    order.stages.flatMap(stage => stage.links).filter(link => link.href.startsWith('/library/')).slice(0, 3)]),
);

// Preserve the separate immunology strand in the subject directory.
export const immunologyPath: (CurriculumLink & { description: string })[] = [
  { title: "Organise the response", href: "/library/innate-adaptive", description: "Distinguish immediate recognition from adaptive specificity." },
  { title: "Present an antigen", href: "/library/antigen-presentation", description: "Connect processing pathways with T-cell recognition." },
  { title: "Follow complement", href: "/library/complement", description: "Separate activation routes from shared effector functions." },
];
