export type Foundation = { title: string; introduction: string; terms: [string, string][]; example: string; prompt: string; answer: string; source: string };
export const foundations: Record<string, Foundation> = {
  anatomy: {
    title: "Orient yourself before naming structures",
    introduction: "Describe the body from the person's perspective. Begin with position, direction and the space a structure occupies; then add its neighbours and function. Right and left belong to the person being described, even when you face them.",
    terms: [["Anatomical position", "The reference posture is upright, facing forward, with palms facing forward."], ["Anterior / posterior", "Toward the front / toward the back in the reference position."], ["Medial / lateral", "Toward / away from the body's midline."], ["Proximal / distal", "Nearer to / farther from a limb's attachment."], ["Transverse plane", "A plane separating upper and lower portions."], ["Mediastinum", "The central thoracic region between the lungs."], ["Lung root", "The group of structures connecting a lung to the mediastinum."], ["Sternal angle", "The palpable junction between the manubrium and body of the sternum."]],
    example: "Describe a nerve as anterior to the lung root before naming its destination. The reference structure makes the relationship testable on a diagram; the word anterior alone does not identify the nerve.",
    prompt: "Your partner faces you. Which side is their right, and what does anterior mean?",
    answer: "Their right is on your left. Anterior still means toward their front; it does not change with the observer's viewpoint.",
    source: "https://openstax.org/books/anatomy-and-physiology-2e/pages/1-6-anatomical-terminology",
  },
  histology: {
    title: "Read a section from architecture to cells",
    introduction: "A microscope section is one cut through a three-dimensional tissue. First identify an outer surface, lining, lumen or repeated unit. Then inspect cells and their surroundings. Use several observations to justify an identification.",
    terms: [["Lumen", "The interior space of a tube or hollow organ."], ["Epithelium", "Cells arranged to cover a surface, line a space or form a gland."], ["Apical / basal", "Toward a lining's free surface / toward its supporting boundary."], ["Matrix", "Material outside cells, including fibres and ground substance."], ["H&E", "A common stain combination: haematoxylin highlights many nucleic-acid-rich structures and eosin many protein-rich structures."], ["Artefact", "An appearance introduced during preparation rather than a normal tissue feature."]],
    example: "A rounded empty profile could be a lumen or a preparation space. Trace its boundary: an organised cellular lining supports a lumen, while a jagged tear crossing structures suggests artefact.",
    prompt: "Why should a dark nucleus alone not identify an organ?",
    answer: "Many organs contain similar nuclei. Architecture, lining, matrix and neighbouring structures provide the discriminating evidence.",
    source: "https://openstax.org/books/biology-2e/pages/4-1-studying-cells",
  },
  "cell-biology": {
    title: "Separate the information from its products",
    introduction: "Follow which molecule is being copied, where the process happens and what product leaves it. DNA replication copies DNA; transcription produces RNA; translation uses an RNA message to assemble a polypeptide. These names describe different operations.",
    terms: [["Nucleotide", "A building unit of a nucleic acid, containing a base, sugar and phosphate."], ["Gene", "A DNA sequence whose expression produces a functional RNA or, through RNA, a protein product."], ["Chromosome", "A DNA molecule packaged with associated proteins."], ["Template", "An existing strand used to guide a complementary product."], ["5′ / 3′", "Labels derived from the sugar's carbon positions that define nucleic-acid strand direction."], ["Antiparallel", "Two strands aligned with opposite 5′-to-3′ directions."]],
    example: "Before interpreting a replication diagram, mark 5′ and 3′ on both templates. New DNA is extended at its 3′ end. An arrow should describe synthesis direction, not merely the direction in which the whole fork moves.",
    prompt: "Does copying DNA directly produce a protein?",
    answer: "No. DNA replication produces DNA. Gene expression connects transcription into RNA with translation into a polypeptide for protein-coding genes.",
    source: "https://openstax.org/books/biology-2e/pages/14-3-basics-of-dna-replication",
  },
  biochemistry: {
    title: "Track matter, energy and reaction rate separately",
    introduction: "For a pathway, write the input, output and location before memorising enzymes. Follow carbon atoms separately from transferred electrons. An enzyme speeds a reaction; it does not supply an unlimited energy source or determine the equilibrium by itself.",
    terms: [["Substrate", "A molecule acted on by an enzyme."], ["Enzyme", "A biological catalyst that increases reaction rate without being consumed in each reaction cycle."], ["ATP", "A nucleotide used to couple many cellular processes to favourable chemical reactions."], ["Oxidation / reduction", "Loss / gain of electrons; the two occur together in an electron-transfer reaction."], ["NADH", "The reduced form of the electron carrier NAD."], ["Pathway", "A connected sequence of reactions whose intermediates link one step to the next."]],
    example: "Pyruvate oxidation releases one carbon as carbon dioxide and produces acetyl-CoA plus NADH. The carbon route and the electron-carrier route answer different questions; NADH is not another name for ATP.",
    prompt: "Why can faster enzyme activity leave the equilibrium position unchanged?",
    answer: "A catalyst changes how quickly equilibrium is approached by lowering the activation barrier. It does not change the reaction's overall free-energy difference.",
    source: "https://openstax.org/books/biology-2e/pages/6-5-enzymes",
  },
  physiology: {
    title: "Name the compartment, gradient and control signal",
    introduction: "When a variable changes, identify what moved, between which compartments, and what drives it. Then distinguish the immediate physical effect from a later regulatory response. A concentration, amount, pressure and flow are different quantities.",
    terms: [["Concentration", "Amount of a substance per unit volume."], ["Gradient", "A difference across distance, such as a concentration or pressure difference."], ["Flow", "Quantity passing a point per unit time."], ["Membrane potential", "An electrical potential difference across a membrane."], ["Homeostasis", "Regulation that keeps internal conditions within a functional range."], ["Negative feedback", "A response that opposes the change that triggered it."]],
    example: "If the same amount of solute occupies twice the volume, its concentration halves. No solute must be removed for concentration to fall. Start with amount divided by volume before adding hormonal regulation.",
    prompt: "A value falls after dilution. Has its total amount necessarily fallen?",
    answer: "No. Check the volume as well as the concentration. Total amount equals concentration multiplied by volume.",
    source: "https://openstax.org/books/anatomy-and-physiology-2e/pages/26-1-body-fluids-and-fluid-compartments",
  },
  genetics: {
    title: "Distinguish inheritance from immune recognition",
    introduction: "For genetics, separate a DNA variant, a genotype and an observed trait. For immunology, identify the recognising cell, what it recognises and the resulting response. The two subjects share molecular tools but ask different questions.",
    terms: [["Allele", "An alternative version of a sequence at a genetic locus."], ["Genotype", "The genetic constitution being considered, such as the alleles at one locus."], ["Phenotype", "An observable characteristic influenced by genotype and context."], ["Antigen", "A structure recognised by an antibody or an adaptive immune receptor in its appropriate presentation context."], ["Innate immunity", "Defence mechanisms using inherited recognition systems."], ["Adaptive immunity", "Antigen-specific lymphocyte responses that can generate memory."]],
    example: "A family relationship helps interpret inheritance; it does not identify a molecular mechanism on its own. Similarly, naming an antigen does not specify whether a response is protective or causes tissue injury.",
    prompt: "Why should an allele and a phenotype not be used as synonyms?",
    answer: "An allele describes a genetic variant; a phenotype describes an observed characteristic. Expression can depend on other variants and environmental context.",
    source: "https://openstax.org/books/biology-2e/pages/12-2-characteristics-and-traits",
  },
  biophysics: {
    title: "Start with units and a stated model",
    introduction: "Write the measured quantity, its unit and the model assumptions. Convert units before substitution, then check whether the result has a plausible sign and scale. A mathematical model answers only the question its assumptions permit.",
    terms: [["SI units", "A coordinated unit system, including metre, kilogram and second."], ["Ratio", "One quantity divided by another; equal units cancel."], ["Proportionality", "A specified relationship between how quantities vary."], ["Logarithm", "The exponent needed to produce a number from a stated base."], ["Focal length", "For a thin lens, the signed distance from the lens to its focal point."], ["Model assumption", "A simplifying condition under which an equation is being used."]],
    example: "For a +0.10 m thin-lens focal length, power is 1/0.10 = +10 dioptres. Substituting 10 centimetres as though it were 10 metres would give the wrong scale. State the sign convention before interpreting a virtual image.",
    prompt: "How many metres are 10 cm, and why does this matter in P = 1/f?",
    answer: "10 cm is 0.10 m. Lens power in dioptres uses focal length in metres, so P is +10 D for a converging lens with that focal length.",
    source: "https://openstax.org/books/university-physics-volume-3/pages/2-4-thin-lenses",
  },
};
