// Editorial routes through released lessons, not new clinical claims or a syllabus.
export const topicGuides = [
  {
    slug: "tissue-identification", title: "How to identify tissues in histology",
    summary: "Build a tissue-identification method using architecture, epithelial boundaries, extracellular matrix, muscle organisation and nervous-tissue clues.",
    audience: "For students beginning microscopy or revising how to justify a tissue identification.",
    preparation: "Start with the four basic tissue families. If section orientation or staining is unfamiliar, spend extra time on the microscopy lesson before naming cells.",
    method: "Work from the overall arrangement to individual cells. For each lesson, record two independent observations before opening its answer explanation. Use the labelled visuals alongside the text; a diagram is not a real microscope section.",
    subjects: ["histology"],
    stages: [
      { id: "histology-foundations-tissues", purpose: "Establish the four tissue families and practise combining independent identification clues." },
      { id: "microscopy", purpose: "Check preparation, staining and section orientation before interpreting a profile." },
      { id: "epithelia", purpose: "Describe the lining and its boundaries before choosing an epithelial category." },
      { id: "connective-tissue", purpose: "Add extracellular features to the cell-based description." },
      { id: "muscle-histology", purpose: "Compare muscle arrangements instead of relying on a single feature." },
      { id: "myelin-and-glial-cells", purpose: "Extend the method to nervous tissue while preserving the distinctions between cells and myelin." },
    ],
    review: "Return to one section or schematic, hide its labels and explain what evidence supports your identification. If two tissue types remain plausible, state which additional feature you would look for. Compare your reasoning with the lesson explanation rather than treating a familiar image as proof.",
    next: { href: "/practice/histology", title: "Apply the method to renal-tubule schematics" },
  },
  {
    slug: "membrane-transport", title: "Membrane transport, osmosis and resting potential",
    summary: "Connect physiology and biophysics through a four-lesson sequence on transport mechanisms, diffusion, osmosis and resting membrane potential.",
    audience: "For students who can name a cell membrane but want a connected explanation of transport and electrical gradients.",
    preparation: "Be comfortable comparing concentrations and following the direction of a gradient. The first lesson supplies the transport framework; later lessons add the physical and electrical models.",
    method: "Keep a short comparison table as you study: what moves, which gradient matters, whether a membrane pathway is needed, and where energy enters the explanation. Use the worked questions to test each row rather than memorising isolated mechanism names.",
    subjects: ["physiology", "biophysics"],
    stages: [
      { id: "fluid-and-membrane-transport", purpose: "Begin with fluid compartments and the distinction between transport mechanisms." },
      { id: "biophysics-diffusion-osmosis", purpose: "Use the physical model to sharpen predictions about diffusion and osmosis." },
      { id: "membrane-potentials", purpose: "Add the electrical contribution when reasoning about membrane gradients." },
      { id: "biophysics-resting-potential", purpose: "Compare the resting-potential model with the earlier transport explanation and check its assumptions." },
    ],
    review: "Choose one worked question and explain the starting conditions, your prediction and the reason for it. Then change one condition and revisit the prediction using the same lesson model. Keep the model's assumptions visible; a calculation alone is not an explanation.",
    next: { href: "/learn/renal/tubular-transport", title: "Continue into renal tubular transport" },
  },
  {
    slug: "dna-to-protein", title: "DNA, inheritance and gene expression: a study sequence",
    summary: "Follow existing genetics and cell-biology lessons from meiosis and inheritance through DNA replication, RNA processing, translation and genetic testing.",
    audience: "For students building a first framework for genetics or separating processes with similar names.",
    preparation: "Review the molecular and cell-biology foundation vocabulary if gene, chromosome or template is unfamiliar. Use the early genetics lessons to keep the inheritance question separate from the molecular process being described.",
    method: "For each step, write down the question being answered, the starting material or situation, and the outcome. Use the lesson's own diagram or example to check the sequence. Keep inheritance patterns and gene-expression mechanisms distinct in your notes.",
    subjects: ["genetics", "cell-biology"],
    stages: [
      { id: "meiosis", purpose: "Start with chromosome behaviour before interpreting inheritance patterns." },
      { id: "inheritance", purpose: "Apply the chromosome framework to the lesson's inheritance examples." },
      { id: "dna-replication", purpose: "Switch explicitly to the molecular question of copying DNA." },
      { id: "rna-processing", purpose: "Follow the processing of an RNA message using the lesson's sequence." },
      { id: "translation", purpose: "Connect the message to polypeptide synthesis without conflating it with replication." },
      { id: "genetic-testing", purpose: "Finish by relating a test to the question it can answer and the limits explained in the lesson." },
    ],
    review: "Explain the sequence aloud, stating which question each lesson answers. When two terms seem interchangeable, return to their inputs and outcomes. For a testing example, include the interpretation limits; do not treat a study exercise as personal clinical advice.",
    next: { href: "/study/genetics", title: "Explore the Genetics and Immunology learning path" },
  },
] as const;
